vich_uploader:
    db_driver: orm

    mappings:
        album_image:
            uri_prefix: /images/albums
            #upload_destination: '%kernel.project_dir%/public/images/albums'
            upload_destination: 'images/albums'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        track_file:
            uri_prefix: /tracks
            #upload_destination: '%kernel.project_dir%/public/tracks'
            upload_destination: 'tracks'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        picture_image:
            uri_prefix: /images/gallery
            #upload_destination: '%kernel.project_dir%/public/images/gallery'
            upload_destination: 'images/gallery'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
