vich_uploader:
    db_driver: orm

    mappings:
        album_image:
            uri_prefix: /images/albums
            upload_destination: '%kernel.project_dir%/public/images/albums'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        track_file:
            uri_prefix: /tracks
            upload_destination: '%kernel.project_dir%/public/tracks'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
